Repository Kaus8ubh/Knowledge-Management-backend, pull requests merged in 2025-04, with the labels that each got.

#5 added edit knowledge card feature
  app/dao/knowledge_card_dao.py
  app/models/__init__.py
  app/models/knowledge_card_model.py
  app/routes/knowledge_card_routes.py
  app/services/knowledge_card_service.py
Labels: enhancement, feature

#6 Fixed Scraper Module
  app/config.py
  app/utils/sraper.py
Labels: bug

#9 created clustering module for clustering of knowledge cards, using em…
  app/dao/__init__.py
  app/dao/card_cluster_dao.py
  app/dao/knowledge_card_dao.py
  app/database/connection.py
  app/main.py
  app/models/__init__.py
  app/models/card_cluster_model.py
  app/routes/__init__.py
  app/routes/card_cluster_routes.py
  app/services/__init__.py
  app/services/card_cluster_service.py
  app/services/knowledge_card_service.py
  app/utils/__init__.py
  app/utils/clustering_module.py
  app/utils/cosine_distance_matrix.py
  app/utils/topic_name_generator.py
  requirements.txt
Labels: enhancement, feature

#15 Feature/share knowledge card
  app/config.py
  app/dao/knowledge_card_dao.py
  app/models/knowledge_card_model.py
  app/routes/knowledge_card_routes.py
  app/services/knowledge_card_service.py
  app/utils/knowledge_card_helper.py
Labels: enhancement

#16 added route to fetch public cards
  app/dao/knowledge_card_dao.py
  app/routes/knowledge_card_routes.py
  app/services/knowledge_card_service.py
Labels: enhancement

#26 Added q&a and Knowledge map fields to pdf generation
  app/services/knowledge_card_service.py
  app/utils/document_generator.py
  requirements.txt
Labels: enhancement

#29 added a feature to customise category of a card
  app/dao/category_dao.py
  app/migrate_existing_categories.py
  app/routes/knowledge_card_routes.py
  app/services/__init__.py
  app/services/category_services.py
  app/services/knowledge_card_service.py
Labels: feature

#30 add tag functionality
  app/dao/knowledge_card_dao.py
  app/models/__init__.py
  app/models/knowledge_card_model.py
  app/routes/knowledge_card_routes.py
  app/services/knowledge_card_service.py
Labels: enhancement

#31 bug fixing in add knowledge card
  app/services/knowledge_card_service.py
Labels: bug
